//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Room_TO_Reservs = new HashSet<Room_TO_Reservs>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int AreaID { get; set; }
        public System.DateTime ReserveDateFrom { get; set; }
        public System.DateTime ReserveDateTo { get; set; }
        public decimal Price { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room_TO_Reservs> Room_TO_Reservs { get; set; }
    }
}
