//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_TO_Reservs
    {
        public int ID { get; set; }
        public int RoomID { get; set; }
        public Nullable<int> ReservID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
